configs:
  username: ""
  password: ""
  keySpace: ""
  clusterId: ""
  clusterRegion: "us-east1"
  tableName: "products"
  tableSchema: "{\"name\":\"products\",\"ifNotExists\":true,\"columnDefinitions\": [ {\"name\":\"id\",\"typeDefinition\":\"uuid\",\"static\":false}, {\"name\":\"name\",\"typeDefinition\":\"text\",\"static\":false}, {\"name\":\"description\",\"typeDefinition\":\"text\",\"static\":false}, {\"name\":\"price\",\"typeDefinition\":\"decimal\",\"static\":false}, {\"name\":\"created\",\"typeDefinition\":\"timestamp\",\"static\":false}],\"primaryKey\": {\"partitionKey\":[\"id\"]},\"tableOptions\":{\"defaultTimeToLive\":0}}"
  logLevel: "debug"
