configs:
  accessKeyId: ""
  secretAccessKey: ""
  awsregion: "us-east-2"
  bucketName: "bucket-name"
  partSize: 5242880
  s3ObjectRolloverMinutes: 10
  logLevel: "debug"
  topicSchemaRequired: false
