name: ci
on:
  push:
    branches:
      - master
    pull_request:
    page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created 

jobs:
  build:
    name: maven build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build with Maven Install
        run: |
          cd s3
          mvn clean install -DskipTests
      - name: Build nar file with Maven
        run: |
          cd s3
          mvn -B package --file pom.xml
